version: "3"
services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  barmanager:
    container_name: barmanager
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - database
    entrypoint: dockerize -wait tcp://database:5432 -timeout 20s docker-entrypoint.sh
    command: npm run migrate:start

volumes:
  pg:
